[tools]
"aqua:go-task/task" = "3.53.1"
"aqua:goreleaser/goreleaser" = "2.18.2"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.8.0"
"aqua:koalaman/shellcheck" = "0.11.0"
"aqua:gotestyourself/gotestsum" = "1.13.0"
node = "25.2.1"
